# Funding options for CCM
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: []          # GitHub Sponsors username(s)
open_collective: [] # Open Collective username
ko_fi: ""           # Ko-fi username
patreon: ""         # Patreon username
